package com.example.demoa.enums;

public enum Company {

//    ---NULL---
DEFAULT,

//    FAICAL, BODY
    NATURES, SHAHNAZ_HUSAIN, VLCC, O3, NUTRIGLOW, JOY, LOTUS, DERMALOGICA, MCAFFEINE, KAYA, SKINQ, RICHFEEL,

//    MANI-PEDI
    MISS_CLAIRE, VOLAMENA,

//    ---MAKEUP, NAILS---
    MYMUSE, SUGAR, TEENITOR, KIYAAN, DEBELLE, BLUE_HEAVEN, TEEN_TEEN, ZUDIO, MAYBELLINE,

//    HAIR
    SCHWARZKOPF, PARADYES, LOREAL, BBLUNT,STREAX, BIOTIQUE, GARNIER, GODREJ
}


